var k=!1,m=this;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}Math.floor(2147483648*Math.random()).toString(36);var aa={};function ba(){this.i=void 0}
function q(a,b,c){switch(typeof b){case "string":r(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if("array"==n(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],q(a,a.i?a.i.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),r(f,
c),c.push(":"),q(a,a.i?a.i.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var s={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ca=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function r(a,b){b.push('"',a.replace(ca,function(a){if(a in s)return s[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return s[a]=e+b.toString(16)}),'"')};function u(a){if("undefined"!==typeof JSON&&void 0!==JSON.stringify)a=JSON.stringify(a);else{var b=[];q(new ba,a,b);a=b.join("")}return a};function v(a,b,c){var d;1>c?d="at least 1":c>b&&(d=0===b?"none":"no more than "+b);if(d)throw Error(a+" failed: Was called with "+c+(1===c?" argument.":" arguments.")+" Expects "+d+".");}
function w(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:aa.S.T.U.assert(k,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}a+=" failed: ";c&&(a+="If provided, ");return a+(d+" argument ")};var x=Math,y={},z=y.p={};function A(){}
var B=z.r={extend:function(a){A.prototype=this;var b=new A;a&&b.O(a);b.q=this;return b},create:function(){var a=this.extend();a.h.apply(a,arguments);return a},h:function(){},O:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},c:function(){return this.q.extend(this)}},C=z.A=B.extend({h:function(a,b){a=this.b=a||[];this.a=void 0!=b?b:4*a.length},toString:function(a){return(a||da).stringify(this)},concat:function(a){var b=this.b,
c=a.b,d=this.a,a=a.a;this.K();if(d%4)for(var e=0;e<a;e++)b[d+e>>>2]|=(c[e>>>2]>>>24-8*(e%4)&255)<<24-8*((d+e)%4);else if(65535<c.length)for(e=0;e<a;e+=4)b[d+e>>>2]=c[e>>>2];else b.push.apply(b,c);this.a+=a;return this},K:function(){var a=this.b,b=this.a;a[b>>>2]&=4294967295<<32-8*(b%4);a.length=x.ceil(b/4)},c:function(){var a=B.c.call(this);a.b=this.b.slice(0);return a},random:function(a){for(var b=[],c=0;c<a;c+=4)b.push(4294967296*x.random()|0);return C.create(b,a)}}),D=y.M={},da=D.Q={stringify:function(a){for(var b=
a.b,a=a.a,c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-8*(d%4)&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d+=2)c[d>>>3]|=parseInt(a.substr(d,2),16)<<24-4*(d%8);return C.create(c,b/2)}},ea=D.R={stringify:function(a){for(var b=a.b,a=a.a,c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>2]>>>24-8*(d%4)&255));return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d++)c[d>>>2]|=(a.charCodeAt(d)&255)<<24-8*(d%
4);return C.create(c,b)}},fa=D.z={stringify:function(a){try{return decodeURIComponent(escape(ea.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(a){return ea.parse(unescape(encodeURIComponent(a)))}},E=z.P=B.extend({reset:function(){this.f=C.create();this.k=0},l:function(a){"string"==typeof a&&(a=fa.parse(a));this.f.concat(a);this.k+=a.a},m:function(a){var b=this.f,c=b.b,d=b.a,e=this.o,f=d/(4*e),f=a?x.ceil(f):x.max((f|0)-this.I,0),a=f*e,d=x.min(4*a,d);if(a){for(var g=0;g<
a;g+=e)this.F(c,g);g=c.splice(0,a);b.a-=d}return C.create(g,d)},c:function(){var a=B.c.call(this);a.f=this.f.c();return a},I:0});z.t=E.extend({h:function(){this.reset()},reset:function(){E.reset.call(this);this.G()},update:function(a){this.l(a);this.m();return this},e:function(a){a&&this.l(a);this.D();return this.g},c:function(){var a=E.c.call(this);a.g=this.g.c();return a},o:16,B:function(a){return function(b,c){return a.create(c).e(b)}},C:function(a){return function(b,c){return ga.s.create(a,c).e(b)}}});
for(var ga=y.n={},F=Math,G=y.p,ha=G.A,G=G.t,H=y.n,ia=[],ja=[],I=2,J=0;64>J;){var K;a:{for(var ka=I,la=F.sqrt(ka),L=2;L<=la;L++)if(!(ka%L)){K=k;break a}K=!0}K&&(8>J&&(ia[J]=4294967296*(F.pow(I,0.5)-(F.pow(I,0.5)|0))|0),ja[J]=4294967296*(F.pow(I,1/3)-(F.pow(I,1/3)|0))|0,J++);I++}
var M=[],H=H.w=G.extend({G:function(){this.g=ha.create(ia.slice(0))},F:function(a,b){for(var c=this.g.b,d=c[0],e=c[1],f=c[2],g=c[3],h=c[4],i=c[5],t=c[6],Q=c[7],j=0;64>j;j++){if(16>j)M[j]=a[b+j]|0;else{var l=M[j-15],p=M[j-2];M[j]=((l<<25|l>>>7)^(l<<14|l>>>18)^l>>>3)+M[j-7]+((p<<15|p>>>17)^(p<<13|p>>>19)^p>>>10)+M[j-16]}l=Q+((h<<26|h>>>6)^(h<<21|h>>>11)^(h<<7|h>>>25))+(h&i^~h&t)+ja[j]+M[j];p=((d<<30|d>>>2)^(d<<19|d>>>13)^(d<<10|d>>>22))+(d&e^d&f^e&f);Q=t;t=i;i=h;h=g+l|0;g=f;f=e;e=d;d=l+p|0}c[0]=c[0]+
d|0;c[1]=c[1]+e|0;c[2]=c[2]+f|0;c[3]=c[3]+g|0;c[4]=c[4]+h|0;c[5]=c[5]+i|0;c[6]=c[6]+t|0;c[7]=c[7]+Q|0},D:function(){var a=this.f,b=a.b,c=8*this.k,d=8*a.a;b[d>>>5]|=128<<24-d%32;b[(d+64>>>9<<4)+15]=c;a.a=4*b.length;this.m()}});y.w=G.B(H);y.u=G.C(H);var ma=y.M.z;
y.n.s=y.p.r.extend({h:function(a,b){a=this.j=a.create();"string"==typeof b&&(b=ma.parse(b));var c=a.o,d=4*c;b.a>d&&(b=a.e(b));for(var e=this.J=b.c(),f=this.H=b.c(),g=e.b,h=f.b,i=0;i<c;i++)g[i]^=1549556828,h[i]^=909522486;e.a=f.a=d;this.reset()},reset:function(){var a=this.j;a.reset();a.update(this.H)},update:function(a){this.j.update(a);return this},e:function(a){var b=this.j,a=b.e(a);b.reset();return b.e(this.J.c().concat(a))}});function N(a,b,c){var d=o;if(typeof a!==b)throw Error("FirebaseTokenGenerator.createToken option "+d+" must be "+c);};Math.random();var O,P,R,S;function na(){return m.navigator?m.navigator.userAgent:null}S=R=P=O=k;var T;if(T=na()){var oa=m.navigator;O=0==T.indexOf("Opera");P=!O&&-1!=T.indexOf("MSIE");R=!O&&-1!=T.indexOf("WebKit");S=!O&&!R&&"Gecko"==oa.product}var pa=P,qa=S,ra=R;var U;if(O&&m.opera){var sa=m.opera.version;"function"==typeof sa&&sa()}else qa?U=/rv\:([^\);]+)(\)|;)/:pa?U=/MSIE\s+([^\);]+)(\)|;)/:ra&&(U=/WebKit\/(\S+)/),U&&U.exec(na());var V=null,W=null;
function ta(a){var b=n(a);if(!("array"==b||"object"==b&&"number"==typeof a.length))throw Error("encodeByteArray takes an array as a parameter");if(!V){V={};W={};for(b=0;65>b;b++)V[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b),W[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(b)}for(var b=W,c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,g=f?a[d+1]:0,h=d+2<a.length,i=h?a[d+2]:0,t=e>>2,e=(e&3)<<4|g>>4,g=(g&15)<<2|i>>6,i=i&63;h||(i=
64,f||(g=64));c.push(b[t],b[e],b[g],b[i])}return c.join("")};function X(a){v("new FirebaseTokenGenerator",1,arguments.length);if("string"!=typeof a)throw Error(w("new FirebaseTokenGenerator",1,k)+"must be a valid firebase namespace secret.");this.N=a}var Y=["FirebaseTokenGenerator"],Z=m;!(Y[0]in Z)&&Z.execScript&&Z.execScript("var "+Y[0]);for(var $;Y.length&&($=Y.shift());)!Y.length&&void 0!==X?Z[$]=X:Z=Z[$]?Z[$]:Z[$]={};
X.prototype.L=function(a,b){v("FirebaseTokenGenerator.createToken",2,arguments.length);if(void 0!==b&&(null==b||"object"!=typeof b))throw Error(w("FirebaseTokenGenerator.createToken",2,!0)+"must be a dictionary of token options.");var c={};for(o in b)switch(o){case "expires":N(b[o],"number","a number.");c.exp=b[o];break;case "notBefore":N(b[o],"number","a number.");c.nbf=b[o];break;case "admin":N(b[o],"boolean","a boolean.");c.admin=b[o];break;case "debug":N(b[o],"boolean","a boolean.");c.debug=b[o];
break;default:throw Error("FirebaseTokenGenerator.createToken unrecognized option: "+o);}c.v=0;c.iat=(new Date).getTime();c.d=a;for(var d=ua(u({alg:"HS256"})),c=ua(u(c)),e=y.u(d+"."+c,this.N).toString(),f=[],g=0;g<e.length;g+=2)f.push(parseInt(e.substr(g,2),16));e=ta(f);e=va(e);return d+"."+c+"."+e};X.prototype.createToken=X.prototype.L;
function ua(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(b[c++]=e>>12|224,b[c++]=e>>6&63|128),b[c++]=e&63|128)}a=ta(b);return va(a)}function va(a){var b=a.indexOf(".");return 0<=b?a.substring(0,b):a}module.exports=X;
